<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MajorController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\StaffController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Frontend Routes
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::post('/contact', [HomeController::class, 'sendContact'])->name('contact.send');

// Blog Routes
Route::get('/blog', [PostController::class, 'index'])->name('blog');
Route::get('/blog/{slug}', [PostController::class, 'show'])->name('blog.show');
Route::get('/category/{category}', [PostController::class, 'category'])->name('blog.category');

// Staff Routes
Route::get('/staff', [StaffController::class, 'index'])->name('staff');
Route::get('/staff/{id}', [StaffController::class, 'show'])->name('staff.show');

// Gallery Routes
Route::get('/gallery', [GalleryController::class, 'index'])->name('gallery');
Route::get('/gallery/{id}', [GalleryController::class, 'show'])->name('gallery.show');

// Academic Routes
Route::get('/majors', [MajorController::class, 'index'])->name('majors');
Route::get('/majors/{code}', [MajorController::class, 'show'])->name('majors.show');

// Registration Routes
Route::get('/registration', [RegistrationController::class, 'create'])->name('registration');
Route::post('/registration', [RegistrationController::class, 'store'])->name('registration.store');

// Authentication Routes 
// (Generated by Laravel Breeze)
require __DIR__.'/auth.php';

// Dashboard Routes 
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin Routes
Route::prefix('admin')->middleware(['auth', 'role:admin'])->name('admin.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    
    // Users Management (Admin only)
    Route::resource('users', UserController::class);
    
    // Content Management
    Route::resource('posts', PostController::class)->except('show');
    Route::resource('staff', StaffController::class)->except('show');
    Route::resource('gallery', GalleryController::class)->except('show');
    Route::resource('majors', MajorController::class)->except('show');
    
    // Registrations Management
    Route::get('registrations', [RegistrationController::class, 'index'])->name('registrations.index');
    Route::get('registrations/{registration}', [RegistrationController::class, 'show'])->name('registrations.show');
    Route::patch('registrations/{registration}/status', [RegistrationController::class, 'updateStatus'])->name('registrations.update-status');
});
